### ISSUE TITLE
Hover: Player Boundaries for new Player shapes

### ISSUE THREAD

**Issue by lukeed** [VIDY/embed.js#135]
"We never updated the boundary logic for new shapes"

Turn out, this is actually incorrect~! We always [read the width/height](https://github.com/VIDY/embed.js/blob/master/src/helpers/util.js#L87-L88) ***BUT*** we weren't accounting for our `scale()` changes. 

Reading clientWidth/clientHeight will give you the _true values_ (aka, what is actually set), but we need the visible/_perceived values_. 

Easy fix:

```js
let { width, height } = player.getBoundingClientRect();
// gives you dimensions AFTER scaling 
```

_Probably related to #126 and #134_

**Comment by eudisd** [comment]
That's what I meant @lukeed, the logic in `getMobilePlayerPosition` does not account for the new dimensions. It assumes that the width/height is the same length (ie a square or circle) but does not account for the rectangular dimensions.  I will fix it in my current branch

**Comment by lukeed** [comment]
The dimensions will change correctly from shape to shape – their widths & heights are always different. But the values we're comparing against are wrong.

See below (console) For example, in this case, we should be using `1400x278` but if it were our SDK, we'd be using `698x137`

<img width="1546" alt="screen shot 2019-01-08 at 1 20 02 pm" src="https://user-images.githubusercontent.com/5855893/50859502-6388e600-1348-11e9-9d46-92a970df282b.png">

**Comment by eudisd** [comment]
I just tried it to be sure, but the width/height are the same regardless of whether we use `getBoundingClientRect` or `clientHeight`, so this does not fix the issues.

Still working on a fix, but things are pointing to a combination of issues relating `getMobilePlayerPosition` and positional side-effects caused by setting `top` and height values in styles instead of the aforementioned function.
