### ISSUE TITLE
Video Choppiness Improvements

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#183]
> the video is bit too choppy still (tested on long video not on the moment where the video restarts after finishing, just as it plays normally and you pull it around screen in chugs). Let’s copy the iOS native controlled delay that it has as you pull it around the screen where there is a velocity that starts and picks up as you pull but also a bit of a polished anchor feel to it where it doesn’t react instantly as you move it around the screen I think that can help mask the choppiness. adding this one again just because the smoothness on moving around will help the polish increase a ton

**Comment by lukeed** [comment]
Sorry, not doable. Spent two days on this almost. The player itself is fully optimized for movement. This is why there's no jitteriness anywhere _except_ Safari. 

The jitter is directly from the video codec working too hard (because it's bad) and so it affects the animation/movement.

This is proven by removing the `video.src` and testing again in iOS. At that point, the poster still shows, but there's ***no jitter*** cuz the video codec isn't invoked.

**Comment by lukeed** [comment]
Closed via #192
